# SPDX-FileCopyrightText: 2026 M5Stack Technology CO LTD
# SPDX-License-Identifier: MIT

import os

Import('env')
with open(env['PROJECT_TOOL_S']) as f:
    exec(f.read())

SRCS = Glob('src/*.c*')
INCLUDE = [ADir('.'), ADir('include'), ADir('ui'), ADir('core')]
PRIVATE_INCLUDE = []   # the FreeType include directories are added below (cp0_statusbar.c)
REQUIREMENTS = ['lvgl_component', 'pthread']   # no cp0_lvgl runtime: Mesh Hop owns the display and the input itself
STATIC_LIB = []
DYNAMIC_LIB = []
DEFINITIONS = [] #'-std=c++20'
DEFINITIONS_PRIVATE = ['-O2']   # the SDK compiles without optimisation by default: LVGL drawing needs it on a Pi Zero 2W
LDFLAGS = ['-Wl,--as-needed']      # do not depend on the libraries LVGL's optional drivers name but nothing uses
LINK_SEARCH_PATH = []
STATIC_FILES = []


SRCS += append_srcs_dir(ADir('ui'))
SRCS += append_srcs_dir(ADir('core'))


lvgl_component = list(filter(lambda x: x['target'] == 'lvgl_component', env['COMPONENTS']))[0]
toolchain_sysroot = os.environ.get('CONFIG_TOOLCHAIN_SYSROOT', '') or '/'

if 'CONFIG_V9_5_LV_USE_SDL' in os.environ:
    lvgl_component['REQUIREMENTS'] += ['SDL2']
    lvgl_component['INCLUDE'] += ['/usr/include/SDL2']
    lvgl_component['DEFINITIONS'] += ['-D_REENTRANT']

if 'CONFIG_V9_5_LV_USE_FREETYPE' in os.environ:
    lvgl_component['REQUIREMENTS'] += ['freetype']
    lvgl_component['INCLUDE'] += [
        f"{os.path.join(toolchain_sysroot, 'usr','include', 'freetype2')}",
        f"{os.path.join(toolchain_sysroot, 'usr','include', 'libpng16')}"
        ]


lvgl_component['DEFINITIONS_PRIVATE'] += ['-O2']

for src in lvgl_component['SRCS']:
    if 'lv_sdl_keyboard.c' in str(src):
        lvgl_component['SRCS'].remove(src)

# cp0_statusbar.c (the launcher's shared top bar) includes the FreeType headers
PRIVATE_INCLUDE += [os.path.join(toolchain_sysroot, 'usr', 'include', 'freetype2')]



env['COMPONENTS'].append({'target':env['PROJECT_NAME'],
                          'SRCS':SRCS,
                          'INCLUDE':INCLUDE,
                          'PRIVATE_INCLUDE':PRIVATE_INCLUDE,
                          'REQUIREMENTS':REQUIREMENTS,
                          'STATIC_LIB':STATIC_LIB,
                          'DYNAMIC_LIB':DYNAMIC_LIB,
                          'DEFINITIONS':DEFINITIONS,
                          'DEFINITIONS_PRIVATE':DEFINITIONS_PRIVATE,
                          'LDFLAGS':LDFLAGS,
                          'LINK_SEARCH_PATH':LINK_SEARCH_PATH,
                          'STATIC_FILES':STATIC_FILES,
                          'REGISTER':'project'
                          })
